import { type FormEvent, useState } from "react";
import { Navigate, useNavigate } from "react-router-dom";
import { useAuth } from "@/context/AuthContext";
import { roleHome } from "@/lib/roleHome";
import { PublicLayout } from "@/components/layout/PublicLayout";
import { ButtonLink, Button } from "@/components/ui/Button";
import { Icon, type IconName } from "@/components/ui/Icon";

const FEATURES: { icon: IconName; title: string; body: string }[] = [
  { icon: "instrument", title: "Instrument registration", body: "Register weighing and measuring instruments once and get a unique instrument ID." },
  { icon: "clipboard", title: "Online verification", body: "Submit verification requests online and track each one from submission to outcome." },
  { icon: "certificate", title: "Digital certificates", body: "Certificates are issued digitally after a passed inspection — view or download a PDF anytime." },
  { icon: "qr", title: "QR-based verification", body: "Every certificate carries a QR code that anyone can scan to confirm it is genuine." },
  { icon: "history", title: "Verification history", body: "Each application keeps a status history so you can see what happened and when." },
  { icon: "clock", title: "Validity tracking", body: "See when a certificate is valid, expiring soon or expired, and plan renewals ahead." },
];

const STEPS = [
  { title: "Register instrument", body: "Business owners add instrument details and location." },
  { title: "Submit verification", body: "Request verification for a registered instrument." },
  { title: "Inspection", body: "An officer or approved test centre inspects it and records the result." },
  { title: "Certification", body: "A passed inspection produces a digital certificate." },
  { title: "Public verification", body: "Anyone can confirm the certificate by ID or QR code." },
];

const TRUST: { icon: IconName; title: string; body: string }[] = [
  { icon: "shield", title: "Secure digital certification", body: "Certificates are generated by the system after an inspection is recorded — not edited by hand." },
  { icon: "route", title: "Traceability", body: "Every instrument and application has a recorded status history, end to end." },
  { icon: "globe", title: "Public verification", body: "Checking a certificate needs no account — just the certificate ID or QR code." },
  { icon: "users", title: "Role-based workflows", body: "Owners, Legal Metrology Officers, test centres and administrators each see only what their role needs." },
];

export default function Landing() {
  const { user, status } = useAuth();
  // Signed-in users keep the previous behaviour: "/" sends them to their dashboard.
  if (status === "loading") return null;
  if (user) return <Navigate to={roleHome(user.role)} replace />;

  return (
    <PublicLayout>
      <Hero />
      <Features />
      <HowItWorks />
      <Trust />
      <FinalCta />
    </PublicLayout>
  );
}

function Hero() {
  return (
    <section className="relative overflow-hidden border-b border-line">
      <div className="container-page grid items-center gap-10 py-12 sm:py-16 lg:grid-cols-[1.15fr_1fr] lg:gap-16 lg:py-24">
        <div className="animate-fade-up">
          <p className="eyebrow">Legal Metrology · Weights &amp; Measures</p>
          <h1 className="mt-4 font-display text-4xl font-semibold leading-[1.08] tracking-tight text-ink sm:text-5xl lg:text-6xl">
            Digital verification &amp; certification for weights and measures.
          </h1>
          <p className="mt-5 max-w-xl text-base text-slate-600 sm:text-lg">
            Register your instruments, request verification online and receive a digital certificate that anyone can
            check for authenticity — with every step tracked from registration to renewal.
          </p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row">
            <ButtonLink to="/register" size="lg">
              Register your business
            </ButtonLink>
            <ButtonLink to="/login" size="lg" variant="secondary">
              Sign in
            </ButtonLink>
          </div>
          <ul className="mt-8 grid gap-2 text-sm text-slate-600 sm:grid-cols-2">
            {["Online verification", "Digital certification", "Transparent status tracking", "Authenticity you can check"].map((t) => (
              <li key={t} className="flex items-center gap-2">
                <Icon name="check" className="h-4 w-4 shrink-0 text-teal" />
                {t}
              </li>
            ))}
          </ul>
        </div>

        <QuickVerify />
      </div>
    </section>
  );
}

// Quick access to the public verification flow. Navigates to the existing
// /verify/:certId route — no new backend call is introduced.
function QuickVerify() {
  const navigate = useNavigate();
  const [id, setId] = useState("");

  function onSubmit(e: FormEvent) {
    e.preventDefault();
    const v = id.trim();
    navigate(v ? `/verify/${encodeURIComponent(v)}` : "/verify");
  }

  return (
    <div className="animate-fade-up rounded-xl border border-line bg-white p-5 shadow-raised sm:p-7" style={{ animationDelay: "80ms" }}>
      <div className="flex items-center gap-3">
        <span className="flex h-11 w-11 items-center justify-center rounded-lg bg-teal-50 text-teal">
          <Icon name="qr" className="h-6 w-6" />
        </span>
        <div>
          <h2 className="font-display text-xl text-ink">Verify a certificate</h2>
          <p className="text-sm text-slate-600">No account needed.</p>
        </div>
      </div>
      <p className="mt-4 text-sm text-slate-600">
        Scan the QR code on the instrument, or enter the certificate ID printed on it.
      </p>
      <form onSubmit={onSubmit} className="mt-4 flex flex-col gap-3 sm:flex-row" role="search">
        <label htmlFor="quick-verify" className="sr-only">
          Certificate ID
        </label>
        <input
          id="quick-verify"
          value={id}
          onChange={(e) => setId(e.target.value)}
          placeholder="Certificate ID"
          autoComplete="off"
          className="h-12 min-w-0 flex-1 rounded-md border border-line bg-white px-3 text-base text-ink placeholder:text-slate-400 focus:border-teal focus:outline-none focus:ring-2 focus:ring-teal/30 sm:text-sm"
        />
        <Button type="submit" size="lg">
          <Icon name="search" className="h-4 w-4" />
          Check
        </Button>
      </form>
    </div>
  );
}

function SectionHead({ eyebrow, title, body }: { eyebrow: string; title: string; body?: string }) {
  return (
    <div className="max-w-2xl">
      <p className="eyebrow">{eyebrow}</p>
      <h2 className="mt-3 font-display text-3xl font-semibold tracking-tight text-ink sm:text-4xl">{title}</h2>
      {body && <p className="mt-3 text-base text-slate-600">{body}</p>}
    </div>
  );
}

function Features() {
  return (
    <section id="features" className="scroll-mt-16 py-14 sm:py-20">
      <div className="container-page">
        <SectionHead
          eyebrow="Platform"
          title="Everything from registration to certificate, in one place."
          body="One system for business owners, inspecting officers and the public."
        />
        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((f) => (
            <div key={f.title} className="rounded-xl border border-line bg-white p-5 shadow-panel sm:p-6">
              <span className="flex h-10 w-10 items-center justify-center rounded-lg bg-teal-50 text-teal">
                <Icon name={f.icon} />
              </span>
              <h3 className="mt-4 font-display text-lg text-ink">{f.title}</h3>
              <p className="mt-1.5 text-sm text-slate-600">{f.body}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function HowItWorks() {
  return (
    <section id="how-it-works" className="scroll-mt-16 border-y border-line bg-paper2/60 py-14 sm:py-20">
      <div className="container-page">
        <SectionHead eyebrow="How it works" title="From instrument to verified certificate in five steps." />
        <ol className="mt-10 grid gap-4 md:grid-cols-5">
          {STEPS.map((s, i) => (
            <li key={s.title} className="relative flex gap-4 rounded-xl border border-line bg-white p-5 shadow-panel md:block">
              <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-ink font-display text-base text-paper">
                {i + 1}
              </span>
              <div>
                <h3 className="font-display text-lg text-ink md:mt-4">{s.title}</h3>
                <p className="mt-1 text-sm text-slate-600">{s.body}</p>
              </div>
            </li>
          ))}
        </ol>
      </div>
    </section>
  );
}

function Trust() {
  return (
    <section id="trust" className="scroll-mt-16 py-14 sm:py-20">
      <div className="container-page grid gap-10 lg:grid-cols-[1fr_1.4fr] lg:gap-16">
        <SectionHead
          eyebrow="Trust"
          title="Built so every certificate can be checked."
          body="The platform keeps a clear record of each instrument and application, and lets the public confirm a certificate without signing in."
        />
        <div className="grid gap-4 sm:grid-cols-2">
          {TRUST.map((t) => (
            <div key={t.title} className="rounded-xl border border-line bg-white p-5 shadow-panel">
              <span className="flex h-10 w-10 items-center justify-center rounded-lg bg-brass-50 text-brass-600">
                <Icon name={t.icon} />
              </span>
              <h3 className="mt-4 font-display text-lg text-ink">{t.title}</h3>
              <p className="mt-1.5 text-sm text-slate-600">{t.body}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function FinalCta() {
  return (
    <section className="container-page pb-14 sm:pb-20">
      <div className="flex flex-col items-start justify-between gap-6 rounded-xl bg-ink px-6 py-10 text-paper sm:px-10 md:flex-row md:items-center">
        <div className="max-w-xl">
          <h2 className="font-display text-2xl text-paper sm:text-3xl">Ready to get your instruments verified?</h2>
          <p className="mt-2 text-sm text-paper2/75">Create an account to register instruments and track verification.</p>
        </div>
        <div className="flex w-full flex-col gap-3 sm:w-auto sm:flex-row">
          <ButtonLink to="/register" size="lg" className="bg-paper text-ink hover:bg-paper2">
            Create an account
          </ButtonLink>
          <ButtonLink to="/verify" size="lg" variant="ghost" className="border border-white/30 text-paper hover:bg-white/10">
            Verify a certificate
          </ButtonLink>
        </div>
      </div>
    </section>
  );
}
